### ISSUE TITLE
Aborted downloads from a tls-listener + hyper server

### ISSUE THREAD

**Issue by darkprokoba** [tmccombs/tls-listener#29] opened 2022-11-18 10:06 UTC
When downloading a file with curl from a tls-listener 0.5.1 + warp 0.3.3 server, the transfer is sometimes (but not always) aborted.

I'm using tls-listener with the openssl feature.

As far as I can tell, this can only be reproduced with transfers larger than roughly 40 KiB. Also, I'm only able to reproduce this over actual network links. It never happens when the client and server are running on the same machine.

I've tried building and running the server on various Linux distros, and I can repro it everywhere. Also, I'm able to reproduce it with curl, and any web browser on any platform.

I've written a small TC to reproduce this issue: https://github.com/darkprokoba/tls-listener-issue-29

Here's how I invoke curl:
```sh
[andrew@andrew ~]$ curl -k https://172.16.0.11:3030/two.js
123456789
...
123456789
123456789
curl: (56) OpenSSL SSL_read: error:0A000126:SSL routines::unexpected eof while reading, errno 0
[andrew@andrew ~]$
```

Here's the trace output of the server
```
[andrew@dragon tls-listener-issue-29]$ RUST_LOG=trace ./target/debug/tls-listener-issue-29 
[2022-11-18T10:22:13Z TRACE mio::poll] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
[2022-11-18T10:22:17Z TRACE mio::poll] registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::conn] Conn::read_head
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::io] received 86 bytes
[2022-11-18T10:22:17Z TRACE tracing::span] parse_headers
[2022-11-18T10:22:17Z TRACE tracing::span::active] -> parse_headers
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::role] Request.parse bytes=86
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::role] Request.parse Complete(86)
[2022-11-18T10:22:17Z TRACE tracing::span::active] <- parse_headers
[2022-11-18T10:22:17Z TRACE tracing::span] -- parse_headers
[2022-11-18T10:22:17Z DEBUG hyper::proto::h1::io] parsed 3 headers
[2022-11-18T10:22:17Z DEBUG hyper::proto::h1::conn] incoming body is empty
[2022-11-18T10:22:17Z TRACE warp::filters::path] "one.js"?: "two.js"
[2022-11-18T10:22:17Z TRACE warp::filters::path] "two.js"?: "two.js"
[2022-11-18T10:22:17Z TRACE warp::filters::fs] file: "two.js"
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Init, keep_alive: Busy }
[2022-11-18T10:22:17Z TRACE tracing::span] encode_headers
[2022-11-18T10:22:17Z TRACE tracing::span::active] -> encode_headers
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::role] Server::encode status=200, body=Some(Unknown), req_method=Some(GET)
[2022-11-18T10:22:17Z TRACE tracing::span::active] <- encode_headers
[2022-11-18T10:22:17Z TRACE tracing::span] -- encode_headers
[2022-11-18T10:22:17Z DEBUG hyper::proto::h1::io] flushed 185 bytes
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Body(Encoder { kind: Length(81929), is_last: false }), keep_alive: Busy }
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::encode] sized write, len = 8192
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::io] buffer.flatten self.len=0 buf.len=8192
[2022-11-18T10:22:17Z DEBUG hyper::proto::h1::io] flushed 8192 bytes
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Body(Encoder { kind: Length(73737), is_last: false }), keep_alive: Busy }
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::encode] sized write, len = 8192
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::io] buffer.flatten self.len=0 buf.len=8192
[2022-11-18T10:22:17Z DEBUG hyper::proto::h1::io] flushed 8192 bytes
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Body(Encoder { kind: Length(65545), is_last: false }), keep_alive: Busy }
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::encode] sized write, len = 8192
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::io] buffer.flatten self.len=0 buf.len=8192
[2022-11-18T10:22:17Z DEBUG hyper::proto::h1::io] flushed 8192 bytes
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Body(Encoder { kind: Length(57353), is_last: false }), keep_alive: Busy }
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::encode] sized write, len = 8192
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::io] buffer.flatten self.len=0 buf.len=8192
[2022-11-18T10:22:17Z DEBUG hyper::proto::h1::io] flushed 8192 bytes
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Body(Encoder { kind: Length(49161), is_last: false }), keep_alive: Busy }
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::encode] sized write, len = 8192
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::io] buffer.flatten self.len=0 buf.len=8192
[2022-11-18T10:22:17Z DEBUG hyper::proto::h1::io] flushed 8192 bytes
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::conn] flushed({role=server}): State { reading: KeepAlive, writing: Body(Encoder { kind: Length(40969), is_last: false }), keep_alive: Busy }
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::encode] sized write, len = 8192
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::io] buffer.flatten self.len=0 buf.len=8192
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::encode] sized write, len = 8192
[2022-11-18T10:22:17Z TRACE hyper::proto::h1::io] buffer.flatten self.len=8192 buf.len=8192
[2022-11-18T10:22:17Z DEBUG hyper::proto::h1::dispatch] error writing: error:0A00007F:SSL routines:ssl3_write_pending:bad write retry:ssl/record/rec_layer_s3.c:1170:
[2022-11-18T10:22:17Z DEBUG hyper::server::conn::spawn_all] connection error: error writing a body to connection: error:0A00007F:SSL routines:ssl3_write_pending:bad write retry:ssl/record/rec_layer_s3.c:1170:
[2022-11-18T10:22:17Z TRACE mio::poll] deregistering event source from poller
```

**Comment by tmccombs** [comment] 2022-11-18 16:12
Does it work as expected if you use hyper without tls-listener?

**Comment by tmccombs** [comment] 2022-11-18 16:28
Also can you reproduce without using warp?

**Comment by darkprokoba** [comment] 2022-11-18 18:39
> Does it work as expected if you use hyper without tls-listener?
Yes, it works as expected without tls-listener, with warp's built-in rustls support.

> can you reproduce without using warp?
I can try...

**Comment by darkprokoba** [comment] 2022-11-18 18:51
Alright, I pushed a new commit in https://github.com/darkprokoba/tls-listener-issue-29 and i'm serving the same content, but this time via hyper directly, cutting warp out of the picture.

This has made the issue much harder to reproduce, but I can still see it if I say

```
$ ab -c 8 -n 640 https://172.16.0.11:3030/
```

**Comment by darkprokoba** [comment] 2022-11-18 18:54
Here's the output of a typical ab run:

```
[andrew@andrew ~]$ ab -c 8 -n 640 https://172.16.0.11:3030/
This is ApacheBench, Version 2.3 <$Revision: 1901567 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 172.16.0.11 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
SSL read failed (1) - closing connection
4015E30E087F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:308:
SSL read failed (1) - closing connection
4015E30E087F0000:error:0A000197:SSL routines:SSL_shutdown:shutdown while in init:ssl/ssl_lib.c:2245:
SSL read failed (1) - closing connection
4015E30E087F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:308:
Completed 500 requests
SSL read failed (1) - closing connection
4015E30E087F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:308:
Completed 600 requests
Finished 640 requests


Server Software:        
Server Hostname:        172.16.0.11
Server Port:            3030
SSL/TLS Protocol:       TLSv1.3,TLS_AES_256_GCM_SHA384,2048,256
Server Temp Key:        X25519 253 bits

Document Path:          /
Document Length:        81929 bytes

Concurrency Level:      8
Time taken for tests:   2.557 seconds
Complete requests:      640
Failed requests:        4
   (Connect: 0, Receive: 0, Length: 4, Exceptions: 0)
Total transferred:      52157088 bytes
...
```

**Comment by tmccombs** [comment] 2022-11-19 05:14
Does the ssl implementation make a difference? For example, is it reproducible with rustls?

**Comment by tmccombs** [comment] 2022-11-19 05:25
From what I can tell from your logs (I haven't had a chance to try reproducing myself yet) it looks like it is failing to write to the stream after tls-listener has accepted a connection and passed it on to the application.  I won't completely discount the possibility that tls-listener is somehow doing something that causes the connection to terminate too soon,  but it definitely isn't clear to me how that would happen.

**Comment by darkprokoba** [comment] 2022-11-19 10:15
I've updated the test case at https://github.com/darkprokoba/tls-listener-issue-29 so that it is trivial to test with warp+rustls (without tls-listener). You can do this by supplying 'rustls' as a command line argument to the tool.

In my own testing, the issue cannot be reproduced without openssl.

I'd go ahead and try to debug this myself, but I'm not sure how to go about it...?

**Comment by darkprokoba** [comment] 2022-11-19 10:40
To summarize, there are now 4 cases in the provided tool:

| cli arg         | passes  |  comments |
| ------------- | ------------- | --------- |
| pure_warp         | OK |  warp + rustls, without tls listener |
| hyper_openssl  |  FAIL  | tls listener + hyper (no warp) |
| hyper_rustls      | OK   | tls listener + hyper (no warp) |
| warp_openssl   |  FAIL | tls listener + warp (the easiest way to repro) |

At least we now know that only openssl is affected.

**Comment by tmccombs** [comment] 2022-11-21 07:49
Unfortunately, I can't seem to reproduce with warp_openssl. 

Which version of openssl are you using? I'm on 3.0.7 (on archlinux).

Have you done (or can you do) anything to confirm the issue is with tls-listener and not the openssl crate, or your installation of openssl?

**Comment by darkprokoba** [comment] 2022-11-21 09:17
I've done most of my testing on Fedora with both openssl 1.1 and 3.0: openssl1.1-1.1.1q-1.fc36.x86_64 and openssl-3.0.5-2.fc36.x86_64.
I can also reproduce this on PhtonOS 4.0 with openssl-3.0.6-2.ph4.x86_64

Now I just tried it with Arch, with its latest openssl
```
[root@archlinux ~]# pacman -Q | grep openssl
openssl 3.0.7-2
```

It is way harder to reproduce compared to Fedora/PhotonOS, but it still happens:
```
$ ab -c 32 -n 6400 https://10.71.216.136:3030/two.js
```
I had to increase the concurrency and the total number of requests in order to reproduce it. Even so it does not happen on every run. But it does happen occasionally. Here's a log of warp_openssl running on Arch:
```
[2022-11-21T09:09:48Z DEBUG hyper::proto::h1::dispatch] error writing: error:0A00007F:SSL routines:ssl3_write_pending:bad write retry:ssl/record/rec_layer_s3.c:1186:
[2022-11-21T09:09:48Z DEBUG hyper::server::conn::spawn_all] connection error: error writing a body to connection: error:0A00007F:SSL routines:ssl3_write_pending:bad write retry:ssl/record/rec_layer_s3.c:1186:
```

**Comment by tmccombs** [comment] 2022-12-30 09:32
Could this be related: https://github.com/tmccombs/tls-listener/pull/31?

Does it help if you increase the handshake timeout (with https://docs.rs/tls-listener/latest/tls_listener/struct.Builder.html#method.handshake_timeout)?

**Comment by tmccombs** [comment] 2024-03-30 05:19
Since there hasn't been any activity on this for two years, and I don't know how to reproduce, I'm going to close this. If anyone is still having problems with this, let me know, and I will re-open it.

**Closed by tmccombs** 2024-03-30 05:19 UTC
